YellowPagesSolution/Frontends/YellowPagesUI/Models/YellowPages/YellowPagesCreateDto.cs
namespace YellowPagesUI.Models.YellowPages;

    public class YellowPagesCreateDto
    {
        public string Name { get; set; }
        public string SurName { get; set; }
        public string Firm { get; set; }
    }

YellowPagesSolution/Frontends/YellowPagesUI/Models/YellowPages/YellowPagesDto.cs
using YellowPagesUI.Models.LocationInformation;
using YellowPagesUI.Models.PhoneInformation;

namespace YellowPagesUI.Models.YellowPages;

public class YellowPagesDto
{
    public YellowPagesDto()
    {
        eMailInformations = new HashSet<EMailInformations.EMailInformationDto>();
        locationInformations = new HashSet<LocationInformationDto>();
        phoneInformations = new HashSet<PhoneInformationDto>();
    }

    public string id { get; set; }
    public string name { get; set; }
    public string surName { get; set; }
    public string firm { get; set; }

    public virtual ICollection<EMailInformations.EMailInformationDto> eMailInformations { get; set; }
    public virtual ICollection<LocationInformationDto> locationInformations { get; set; }
    public virtual ICollection<PhoneInformationDto> phoneInformations { get; set; }
}

YellowPagesSolution/Frontends/YellowPagesUI/Models/YellowPages/YellowPagesReportCreateDto.cs
namespace YellowPagesUI.Models.YellowPages;

public class YellowPagesReportCreateDto
{
    public string Location { get; set; }
}

YellowPagesSolution/Frontends/YellowPagesUI/Controllers/YellowPagesController.cs
using YellowPages.Shared.Dtos;
using YellowPagesUI.Business.Abstract;
using IEMailInformationService = YellowPagesUI.Business.Abstract.IEMailInformationService;

namespace YellowPagesUI.Controllers
{
    [Microsoft.AspNetCore.Authorization.AuthorizeAttribute]
    public class YellowPagesController : Microsoft.AspNetCore.Mvc.Controller
    {
        private readonly IEMailInformationService _eMailInformationService;
        private readonly IPhoneInformationService _phoneInformationService;
        private readonly ILocationInformationService _locationInformationService;
        private readonly IYellowPagesService _yellowPagesService;
        private readonly IReportService _reportService;

        private readonly YellowPages.Shared.Services.ISharedIdentityService _sharedIdentityService;

        public YellowPagesController(IEMailInformationService eMailInformationService, IPhoneInformationService phoneInformationService, ILocationInformationService locationInformationService, YellowPages.Shared.Services.ISharedIdentityService sharedIdentityService, IYellowPagesService yellowPagesService, IReportService reportService)
        {
            _eMailInformationService = eMailInformationService;
            _phoneInformationService = phoneInformationService;
            _locationInformationService = locationInformationService;
            _sharedIdentityService = sharedIdentityService;
            _yellowPagesService = yellowPagesService;
            _reportService = reportService;
        }
        public async Task<Microsoft.AspNetCore.Mvc.IActionResult> Index()
        {
            return View(await _yellowPagesService.GetAllContactAsync());

        }
        public async Task<Microsoft.AspNetCore.Mvc.IActionResult> Create()
        {
            var models = await _yellowPagesService.GetAllContactAsync();

            ViewBag.contactsList = models;

            return View();
        }

        [Microsoft.AspNetCore.Mvc.HttpPostAttribute]
        public async Task<Microsoft.AspNetCore.Mvc.IActionResult> Create(YellowPagesCreateDto contactCreateInput)
        {

            await _yellowPagesService.CreateAsync(contactCreateInput);

            return RedirectToAction(nameof(Index));
        }

        public async Task<Microsoft.AspNetCore.Mvc.IActionResult> AddEMail()
        {
            return  View();
        }

        [Microsoft.AspNetCore.Mvc.HttpPostAttribute]
        public async Task<Microsoft.AspNetCore.Mvc.IActionResult> AddEMail(string id, string email)
        {
          EMailInformationCreateDto model = new();
            model.ContactId = id;
            model.EMail = email;
            _eMailInformationService.CreateAsync(model);
            return RedirectToAction(nameof(Index));
        }
        public async Task<Microsoft.AspNetCore.Mvc.IActionResult> EmailDelete(string id)
        {
            var data = await _yellowPagesService.GetByIdAsync(id);
            ViewBag.email = data;
            return View();
        }
        public async Task<Microsoft.AspNetCore.Mvc.IActionResult> EmailDelete2(string id)
        {
            var result = await _eMailInformationService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }


        public async Task<Microsoft.AspNetCore.Mvc.IActionResult> AddPhone(string id)
        {
            return View();
        }
        [Microsoft.AspNetCore.Mvc.HttpPostAttribute]
        public async Task<Microsoft.AspNetCore.Mvc.IActionResult> AddPhone(string id, string phone)
        {

           PhoneInformationCreateDto model = new();
            model.ContactId = id;
            model.Phone = phone;
            _phoneInformationService.CreateAsync(model);
            return RedirectToAction(nameof(Index));
        }
        public async Task<Microsoft.AspNetCore.Mvc.IActionResult> PhoneDelete(string id)
        {
            var data = await _yellowPagesService.GetByIdAsync(id);

            ViewBag.phone = data;

            return View();
        }
        public async Task<Microsoft.AspNetCore.Mvc.IActionResult> PhoneDelete2(string id)
        {
            var result = await _phoneInformationService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }


        public async Task<Microsoft.AspNetCore.Mvc.IActionResult> AddLocation(string id)
        {
            return View();
        }

        [Microsoft.AspNetCore.Mvc.HttpPostAttribute]
        public async Task<Microsoft.AspNetCore.Mvc.IActionResult> AddLocation(string id, string location)
        {

            LocationInformationCreateDto model = new();
            model.ContactId = id;
            model.Location = location;
            _locationInformationService.CreateAsync(model);

            return RedirectToAction(nameof(Index));
        }
        public async Task<Microsoft.AspNetCore.Mvc.IActionResult> LocationDelete(string id)
        {
            var data = await _yellowPagesService.GetByIdAsync(id);

            ViewBag.location = data;

            return View();
        }
        public async Task<Microsoft.AspNetCore.Mvc.IActionResult> LocationDelete2(string id)
        {
            var result = await _locationInformationService.DeleteAsync(id);

            return RedirectToAction(nameof(Index));
        }


        public async Task<Microsoft.AspNetCore.Mvc.IActionResult> Delete(string id)
        {
            await _yellowPagesService.DeleteAsync(id);

            return RedirectToAction(nameof(Index));
        }

        public async Task<Microsoft.AspNetCore.Mvc.IActionResult> AddReport(string id)
        {
            ViewBag.reports = await _reportService.GetAllReportAsync();

            return View(await _yellowPagesService.GetAllContactAsync());

        }
        

        public async Task<Microsoft.AspNetCore.Mvc.IActionResult> AddReport2(string location)
        {

            _yellowPagesService.AddReport(location);

            return RedirectToAction(nameof(AddReport));
        }

        public async Task<Microsoft.AspNetCore.Mvc.IActionResult> ReportDetails(string location)
        {

          var report= await _reportService.ReportById(location);

            return View(report);

        }

    }
}

YellowPagesSolution/Frontends/YellowPagesUI/Views/YellowPages/AddEmail.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using EMailInformationCreateDto = YellowPages.Shared.Dtos.EMailInformationCreateDto
@model EMailInformationCreateDto

<div class="row">
    <div class="col-md-8 offset-md-2">

        <div class="card">
            <div class="card-body">
                <h5 class="card-title">EMail Ekleme İşlemi</h5>

                <form asp-controller="YellowPages" asp-action="AddEmail" method="post" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly"></div>

                    <input type="hidden" asp-for="ContactId" />
                    <div class="mb-3">
                        <label asp-for="EMail" class="form-label"></label>
                        <input asp-for="EMail" class="form-control" />
                        <span class="text-danger" asp-validation-for="EMail"></span>
                    </div>
                    <button type="submit" class="btn btn-primary">EMail Kaydet</button>
                </form>
            </div>
        </div>
    </div>
</div>

YellowPagesSolution/Frontends/YellowPagesUI/Views/YellowPages/AddLocation.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@using LocationInformationCreateDto = YellowPages.Shared.Dtos.LocationInformationCreateDto
@model LocationInformationCreateDto

<div class="row">
    <div class="col-md-8 offset-md-2">

        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Location Ekleme İşlemi </h5>

                <form asp-controller="YellowPages" asp-action="AddLocation" method="post" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly"></div>

                    <input type="hidden" asp-for="ContactId" />
                    <div class="mb-3">
                        <label asp-for="Location" class="form-label"></label>
                        <input asp-for="Location" class="form-control" />
                        <span class="text-danger" asp-validation-for="Location"></span>
                    </div>
                    <button type="submit" class="btn btn-primary">Location Kaydet</button>
                </form>
            </div>
        </div>
    </div>
</div>

YellowPagesSolution/Frontends/YellowPagesUI/Views/YellowPages/AddPhone.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@using PhoneInformationCreateDto = YellowPages.Shared.Dtos.PhoneInformationCreateDto
@model PhoneInformationCreateDto

<div class="row">
    <div class="col-md-8 offset-md-2">

        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Phone Ekleme İşlemi</h5>

                <form asp-controller="YellowPages" asp-action="AddPhone" method="post" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly"></div>

                    
                    <input type="hidden" asp-for="ContactId" />
                    <div class="mb-3">
                        <label asp-for="Phone" class="form-label"></label>
                        <input asp-for="Phone" class="form-control" />
                        <span class="text-danger" asp-validation-for="Phone"></span>
                    </div>


                    <button type="submit" class="btn btn-primary">Phone Kaydet</button>
                </form>
            </div>
        </div>
    </div>
</div>

YellowPagesSolution/Frontends/YellowPagesUI/Views/YellowPages/AddReport.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using YellowPages.Shared.Dtos
@using YellowPagesDto = YellowPages.Shared.Dtos.YellowPagesDto
@model List<YellowPagesDto>
@{
    var reports = ViewBag.reports as List<ReportDto>;

}
<div class="row">
    <div class="col-md-12">

        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Locations</h5>

                @if (Model.Any())
                {
                    <table class="table table-striped table-bordered">
                        <thead>
                        <tr>
                            <th>Location</th>
                            <th>İşlemler</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach (var item in Model)
                        {
                            @if (item.LocationInformations as List<LocationInformationDto> != null)
                            {
                                @foreach (var item2 in item.LocationInformations as List<LocationInformationDto>)
                                {
                                    <tr>
                                        <td>@item2.Location</td>
                                        <td>
                                            <a asp-controller="YellowPages" asp-action="AddReport2" asp-route-location="@item2.Location" class="btn btn-success btn-sm">Rapor oluştur</a>
                                        </td>
                                    </tr>
                                }
                            }
                        }
                        </tbody>
                    </table>
                }
                else
                {
                    <div class="alert alert-info">
                        Kayıtlı Locations bulunamadı
                    </div>
                }
            </div>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-md-12">

        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Reports</h5>

                @if (reports.Any())
                {
                    <table class="table table-striped table-bordered">
                        <thead>
                        <tr>
                            <th>Location</th>
                            <th>İşlemler</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach (var item in reports)
                        {
                            <tr>
                                <td>@item.Location</td>
                                <td>
                                    <a asp-controller="YellowPages" asp-action="ReportDetails" asp-route-location="@item.Id" class="btn btn-success btn-sm">Ayrıntılar</a>
                                </td>
                            </tr>
                        }
                        </tbody>
                    </table>
                }
                else
                {
                    <div class="alert alert-info">
                        Kayıtlı Report bulunamadı
                    </div>
                }
            </div>
        </div>
    </div>
</div>

YellowPagesSolution/Frontends/YellowPagesUI/Views/YellowPages/Create.cshtml
@using YellowPagesCreateDto = YellowPages.Shared.Dtos.YellowPagesCreateDto
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model YellowPagesCreateDto
<div class="row">
    <div class="col-md-8 offset-md-2">

        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Yellow Page Ekleme İşlemi </h5>

                <form asp-controller="YellowPages" asp-action="Create" method="post" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly"></div>


                    <div class="mb-3">
                        <label asp-for="Name" class="form-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span class="text-danger" asp-validation-for="Name"></span>
                    </div>

                    <div class="mb-3">
                        <label asp-for="SurName" class="form-label"></label>
                        <input asp-for="SurName" class="form-control" />
                        <span class="text-danger" asp-validation-for="SurName"></span>
                    </div>

                    <div class="mb-3">
                        <label asp-for="Firm" class="form-label"></label>
                        <textarea asp-for="Firm" class="form-control"></textarea>
                        <span class="text-danger" asp-validation-for="Firm"></span>
                    </div>

                    

                    <button type="submit" class="btn btn-primary">Yellow Pages Kaydet</button>
                </form>
            </div>
        </div>
    </div>
</div>

YellowPagesSolution/Frontends/YellowPagesUI/Views/YellowPages/DeleteEmail.cshtml
@using YellowPages.Shared.Dtos
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    YellowPagesDto contact = ViewBag.contact as YellowPagesDto;
}

<div class="row">
    <div class="col-md-12">

        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Yellow Pages</h5>

                @*     <a asp-controller="Courses" asp-action="Create" class="btn btn-primary mb-3">Kurs oluştur</a>*@
                @if (contact.EMailInformations.Any())
                {
                    <table class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Firm</th>
                                <th>SurName</th>
                                <th>EMailInformations</th>
                                <th>Id</th>
                                <th>Id</th>
                                <th>Id</th>
                                <th>İşlemler</th>
                            </tr>
                        </thead>
                        <tbody>

                            <tr>
                                <td>@contact.Name</td>
                                <td>@contact.Firm</td>
                                <td>@contact.SurName</td>
                                <td>
                            <tr>
                                <th>Location</th>
                                <th>ContactId</th>

                                <th>Id</th>
                            </tr>
                     

                                    @{
                                        @foreach (var item in contact.EMailInformations as List<LocationInformationDto>)
                                        {
                                    <tr>
                                        <td>@item.Location</td>
                                        <td>@item.ContactId</td>

                                        <td>@item.Id</td>
                                    </tr>
                                        }




                                    }

                        <td>@contact.Id</td>
                        </tr>

                        </tbody>
                    </table>
                }
                else
                {
                    <div class="alert alert-info">
                        Kayıtlı Yellow Page bulunamadı
                    </div>
                }
            </div>
        </div>
    </div>
</div>

YellowPagesSolution/Frontends/YellowPagesUI/Views/YellowPages/EmailDelete.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using YellowPages.Shared.Dtos
@{
    var contact = ViewBag.email as YellowPagesDto;
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Yellow Pages</h5>
               @{
                   @if (contact != null)
                   {
                       <table class="table table-striped table-bordered">
                           <thead>
                           <tr>
                               <th>İsim</th>
                               <th>Soyad</th>
                               <th>Firma</th>
                           </tr>
                           </thead>
                           <tbody>
                           <tr>
                               <td>@contact.Name</td>
                               <td>@contact.SurName</td>
                               <td>@contact.Firm</td>
                           </tr>
                           </tbody>
                       </table>
                       <table class="table table-striped table-bordered">
                           @if (contact.EMailInformations as List<EMailInformationDto> != null)
                           {
                               <thead>
                               <tr>
                                   <th>EMail</th>
                                   <th>İşlemler</th>
                               </tr>
                               </thead>
                               @foreach (var item in contact.EMailInformations as List<EMailInformationDto>)
                               {
                                   <tbody>
                                   <tr>
                                       <td>@item.EMail</td>
                                       <td>
                                                <a asp-controller="YellowPages" asp-action="EmailDelete2" asp-route-id="@item.Id" class="btn btn-danger btn-sm">Sil</a>
                                       </td>
                                   </tr>
                                   </tbody>
                               }

                           }


                       </table>
                   }
                   else
                   {
                       <div class="alert alert-info">
                           Kayıtlı Yellow Page bulunamadı
                       </div>
                   }
               }
            </div>
        </div>
    </div>
</div>

YellowPagesSolution/Frontends/YellowPagesUI/Views/YellowPages/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using YellowPagesDto = YellowPages.Shared.Dtos.YellowPagesDto
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model List<YellowPagesDto>

<div class="row">
    <div class="col-md-12">

        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Yellow Pages</h5>

                @if (Model.Any())
                {
                    <table class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>İsim</th>
                                <th>Soy isim</th>
                                <th>Kurs isim</th>
                                <th>İşlemler</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.Name</td>
                                    <td>@item.SurName</td>
                                    <td>@item.Firm</td>
                                    <td>
                                        <a asp-controller="YellowPages" asp-action="AddEmail" asp-route-id="@item.Id" class="btn btn-success btn-sm">EMail Ekle</a>
                                        <a asp-controller="YellowPages" asp-action="EmailDelete" asp-route-id="@item.Id" class="btn btn-success btn-sm">EMail Sil</a><br>

                                        <a asp-controller="YellowPages" asp-action="AddPhone" asp-route-id="@item.Id" class="btn btn-success btn-sm">Telefon Ekle</a>
                                        <a asp-controller="YellowPages" asp-action="PhoneDelete" asp-route-id="@item.Id" class="btn btn-success btn-sm">Telefon Sil</a><br>

                                        <a asp-controller="YellowPages" asp-action="AddLocation" asp-route-id="@item.Id" class="btn btn-success btn-sm">Location Ekle</a>
                                        <a asp-controller="YellowPages" asp-action="LocationDelete" asp-route-id="@item.Id" class="btn btn-success btn-sm">Location Sil</a><br>

                                        <a asp-controller="YellowPages" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm">Yellow Page Sil</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                }
                else
                {
                    <div class="alert alert-info">
                        Kayıtlı Yellow Page bulunamadı
                    </div>
                }
            </div>
        </div>
    </div>
</div>

YellowPagesSolution/Frontends/YellowPagesUI/Views/YellowPages/LocationDelete.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using YellowPages.Shared.Dtos
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    var contact = ViewBag.location as YellowPagesDto;

    var d = contact;
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Yellow Pages</h5>
                @{
                    if (contact != null)
                    {
                        <table class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>İsim</th>
                                    <th>Soyad</th>
                                    <th>Firma</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>@contact.Name</td>
                                    <td>@contact.SurName</td>
                                    <td>@contact.Firm</td>
                                </tr>
                                <tr>
                                    @if ((@contact.LocationInformations as List<LocationInformationDto>) != null)
                                    {
                                    <tr>
                                        <th>Location</th>
                                        <th>İşlemler</th>
                                    </tr>
                                        @foreach (var item in @contact.LocationInformations as List<LocationInformationDto>)
                                        {
                                        <tr>
                                            <td>@item.Location</td>
                                            <td>   <a asp-controller="YellowPages" asp-action="LocationDelete2" asp-route-id="@item.Id" class="btn btn-danger btn-sm">Sil</a></td>
                                        </tr>



                                        }


                                    }
                                </tr>
                            </tbody>
                        </table>
                    }
                    else
                    {
                        <div class="alert alert-info">
                            Kayıtlı Yellow Page bulunamadı
                        </div>
                    }
                }
            </div>
        </div>
    </div>
</div>

YellowPagesSolution/Frontends/YellowPagesUI/Views/YellowPages/PhoneDelete.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using YellowPages.Shared.Dtos
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    var contact = ViewBag.phone as YellowPagesDto;

    var d = contact;
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">YellowPages</h5>
                @{
                    if (contact != null)
                    {
                        <table class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>İsim</th>
                                    <th>Soyad</th>
                                    <th>Firma</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>@contact.Name</td>
                                    <td>@contact.SurName</td>
                                    <td>@contact.Firm</td>
                                </tr>
                                <tr>
                                    @if ((@contact.PhoneInformations as List<PhoneInformationDto>) != null)
                                    {
                                    <tr>
                                        <th>Phone</th>
                                        <th>İşlemler</th>


                                    </tr>
                                        @foreach (var item in @contact.PhoneInformations as List<PhoneInformationDto>)
                                        {
                                        <tr>
                                            <td>@item.Phone</td>
                                            <td>   <a asp-controller="YellowPages" asp-action="PhoneDelete2" asp-route-id="@item.Id" class="btn btn-danger btn-sm">Sil</a></td>
                                        </tr>



                                        }


                                    }
                                </tr>
                            </tbody>
                        </table>
                    }
                    else
                    {
                        <div class="alert alert-info">
                            Kayıtlı Phone bulunamadı
                        </div>
                    }
                }
            </div>
        </div>
    </div>
</div>

YellowPagesSolution/Frontends/YellowPagesUI/Views/YellowPages/ReportDetails.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using ReportDto = YellowPages.Shared.Dtos.ReportDto
@model ReportDto
<div class="row">

    <div class="col-md-9">

        <div class="card">
            <div class="card-body">

                <h5 class="card-title">Rapor Ayrıntıları</h5>

                <table class="table table-striped">

                    <tr>
                        <td>Oluşturma Tarihi</td>
                        <td>@Model.CreatedTime</td>
                    </tr>
                    <tr>
                        <td>Location da kayıtlı telefon sayısı</td>
                        <td>@Model.LocationPhoneCount</td>
                    </tr>
                    <tr>
                        <td>Location daki yellow pages sayısı</td>
                        <td>@Model.LocationContactCount</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>